# Generated by Django 5.1 on 2024-09-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheitem',
            name='completion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cacheitem',
            name='prompts',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cacheitem',
            name='vectors',
            field=models.JSONField(null=True),
        ),
    ]
